### ISSUE TITLE
Matching using non-mutating method on mutable input

### ISSUE THREAD

**Issue by canac** [audunhalland/unimock#40]
Thanks for this great library! It's been super helpful to be and I hope it gets more adoption. I'm trying to upgrade my app from v0.3 to v0.5. The last thing I'm hung up on is calling a non-mutating method in a `matching!` clause on a mutable input. For example:

```rs
#[entrait(pub Exec, mock_api=ExecMock)]
fn exec(_deps: &impl std::any::Any, command: &mut std::process::Command) -> Result<(ExitStatus, String)> {
   // ...
}

Unimock::new(
    dependencies::ExecMock
        // Error: no method named `get_program` found for reference `&PhantomMut<&std::process::Command>` in the current scope
        .each_call(matching!((command) if command.get_program() == "editor"))
        .answers(|_| Ok((ExitStatusExt::from_raw(1), String::new())))
);
```

`command` is a `&mut std::process::Command` and `Command::get_program()` takes a non-mutable `&self`, but `unimock` won't let me call that method even though I'm not mutating anything in the matcher. Am I missing something? Is there a workaround?

Thanks again for your work on this!

**Comment by audunhalland** [comment]
The only workaround I can think of without changing anything in unimock is to introduce a dummy &mut argument at the end of the argument list:

```
fn exec(.., command: &mut Command, dummy: &mut ());
```

Then that argument will become the `PhantomMut` and can actually be mutated within the mock handler.

The &mut arguments can't both be matched against in an argument tuple _and_ be mutable at the same time, because the generic associated types in `MockFn` have to limit themselves to a finite number of lifetimes (there's one lifetime in `type Inputs<'i>`).

**Comment by canac** [comment]
@audunhalland Adding the dummy argument works. thanks for your help! Feel free to either close this ticket or leave it open if you want to try to improve things in a future release.

**Comment by audunhalland** [comment]
I worked on this during the weekend, and I think I've found a somewhat sensible solution to parameter mutation. There is a [branch](https://github.com/audunhalland/unimock/tree/apply-fn) with reworked mutation support. It was a bit difficult to find a good tradeoff between making things flexible on one side and ergonomic on the other. There's no special "mutation parameter" anymore, and it's still possible to actually mutate every `&mut` parameter in a user-supplied function/closure, now called `.applies(..)` instead of `.answers(..)`. The `.applies(..)` solution is a tiny bit more verbose to use though, because its accepted closure can't have a generic return value, which was the case with `anwers`.

I will likely make a `next` branch soon, and this will be the basis of a new major version.

**Comment by audunhalland** [comment]
[0.6.0](https://github.com/audunhalland/unimock/releases/tag/0.6.0) has been released, which fixes this. Now entrait also needs to be updated.

**Comment by canac** [comment]
@audunhalland That's amazing! I look forward to trying it out after the entrait update.

**Comment by audunhalland** [comment]
@canac 

> I look forward to trying it out after the entrait update.

[entrait 0.7.0](https://github.com/audunhalland/entrait/releases/tag/0.7.0) just released.
