### ISSUE TITLE
Unimock with type Err; traits

### ISSUE THREAD

**Issue by Qkessler** [audunhalland/unimock#56]
Hi there!

I'm trying out unimock for doing my unit testing with my traits. Has a great value proposition, enjoying it.

I'm sure you have thought of this (since you have implemented unimock for std traits), but wanted to flag and ask for directions. 

I have a trait that uses `type Err;` that then returns in a result with `Self::Err`. When adding the unimock derive macro, it forces you to provide a concrete type. Can't add a default type because it's unstable.

What do you recommend? If you need more info, I'll send an example once I'm at work.

Best,
Quique.

**Comment by Qkessler** [comment]
Hi there!

Thanks for the pointers, very helpful. I'll try my best to understand that. Just to make sure I got your approach right:

1. You enforce that all implementors of the trait also define the trait `ErrorType` with the intention of using their Error definiton.
2. You define the actual value AND the Unimock value, with the intention of actually having both known to the `unimock` derive macro?

Need to dive deeper, please, correct me if wrong!

Best,
Quique.

**Comment by audunhalland** [comment]
Maybe there's a small misunderstanding: https://docs.rs/embedded-hal/latest/embedded_hal/ is a 3rd-party crate with a lot of exported traits that I wanted to integrate with unimock. The implementations in [https://github.com/audunhalland/unimock/tree/main/src/mock] all use `mirror=SomeThirdPartyTrait`, so they don't (re-)define the traits themselves, only the _implementations_ of those 3rd-party traits `for Unimock`. The macro needs to see the structure of the trait it's supposed to generate mock implementation for, that's why those traits look "duplicated".

**Comment by Qkessler** [comment]
I was able to get that to compile, using the same pattern. 

Running into an issue, not the same, though now that I'm here and before closing the issue, here it goes:
```
error[E0277]: the trait bound `Result<aws_sdk_s3::operation::get_object::GetObjectOutput, unimock::Unimock>: Clone` is not satisfied
   --> crates/cervantes-tls/src/lib.rs:285:22
    |
285 |             .returns(Ok(GetObjectOutput::builder().build()));
    |              ------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `Result<aws_sdk_s3::operation::get_object::GetObjectOutput, unimock::Unimock>`
    |              |
    |              required by a bound introduced by this call
    |
    = note: required for `Result<aws_sdk_s3::operation::get_object::GetObjectOutput, unimock::Unimock>` to implement `Clone`
    = note: required for `Result<aws_sdk_s3::operation::get_object::GetObjectOutput, unimock::Unimock>` to implement `IntoReturn<Owning<Result<aws_sdk_s3::operation::get_object::GetObjectOutput, unimock::Unimock>>>`
note: required by a bound in `DefineMultipleResponses::<'p, F, O>::returns`
   --> /Volumes/workplace/Cervantes/src/CervantesService/build/private/cargo-home/registry/src/-fa4b2c3f5ceba8f7/unimock-0.6.5/src/build.rs:264:12
    |
262 |     pub fn returns<T>(mut self, value: T) -> Quantify<'p, F, O>
    |            ------- required by a bound in this associated function
263 |     where
264 |         T: IntoReturn<F::OutputKind>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `DefineMultipleResponses::<'p, F, O>::returns`
help: consider borrowing here
    |
285 |             .returns(&Ok(GetObjectOutput::builder().build()));
    |                      +
```

Here's my test:
```
    #[tokio::test]
    async fn material_retriever_uses_default_region_if_none() {
        let clause = S3ClientMock::get_object
            .each_call(matching!())
            .returns(Ok(GetObjectOutput::builder().build()));
    ....
```

The get_object method returns a Result, and the mock has Unimock as the Err side (following the pattern above).

**Comment by audunhalland** [comment]
So I guess it's not the case that `GetMockOutput: Clone`.

In this case there are two things you could do:
* use [some_call](https://docs.rs/unimock/latest/unimock/trait.MockFn.html#method.some_call) instead of `each_call`, some_call-call patterns will only work the first time they're called, since it's not clonable.
* use [answers](https://docs.rs/unimock/latest/unimock/build/struct.DefineMultipleResponses.html#method.answers) instead of `returns(value)`.

**Comment by Qkessler** [comment]
Thanks so much! Feel free to close! Thanks for your work here!

Enrique Kessler Martínez.
c/ Jiménez de la espada, Cartagena, España.
